test skip job

diff --git a/.github/workflows/run_tests.yaml b/.github/workflows/run_tests.yaml
--- a/.github/workflows/run_tests.yaml
+++ b/.github/workflows/run_tests.yaml
@@ -26,7 +26,7 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
           poll-interval: 20
   Pgskipper-Pipeline:
-    if: ${{ github.actor != 'dependabot[bot]' }}
+    if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.user.login != 'dependabot[bot]' }}
     needs: Wait-for-images
     uses: Netcracker/qubership-test-pipelines/.github/workflows/pgskipper.yaml@acf44dc8f22430d11eb93a679bf54e99b69ee6a2 #v1.5.0
     with:
@@ -36,4 +36,16 @@ jobs:
     secrets:
       AWS_S3_ACCESS_KEY_ID: ${{secrets.AWS_S3_ACCESS_KEY_ID}}
       AWS_S3_ACCESS_KEY_SECRET: ${{secrets.AWS_S3_ACCESS_KEY_SECRET}}
+  Tests-Result:
+    if: always()
+    needs: Pgskipper-Pipeline
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check tests status
+        run: |
+          if [[ "${{ needs.Pgskipper-Pipeline.result }}" != "success" && "${{ needs.Pgskipper-Pipeline.result }}" != "skipped" ]]; then
+            echo "Tests were failed"
+            exit 1
+          fi
+          echo "All tests completed successfully or not required"
 
